# Generated by Django 4.0.3 on 2022-05-25 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_lastlogin_remove_user_lastlogout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
